### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by jesseflorig**
Overview of changes:

- Converted `Alert.jsx` to a functional component using React Hooks
- Extended `Alert.jsx` to accept `type` and `timeout`
- Updated `showAlert` emitter events

Unintended change:
- Converted tabs from 4 spaces to 2.

If you'll otherwise accept the intended changes, I will update this PR to restore tabs to 4 spaces.

Cheers!

### CODE REVIEW

**Comment by rvazarkar** [comment]
So whats the benefit of the functional component part? Not familiar with react hooks yet

**Comment by jesseflorig** [comment]
> So whats the benefit of the functional component part?

Functional components are easier to read, no `this`, easier to test and easier to optimize than classes. Hooks basically bring state, component lifecycle and a bunch of other React features to functional components. [Source](https://reactjs.org/docs/hooks-intro.html).

**Comment by rvazarkar** [comment]
Interesting. I'm more than willing to accept this PR after I test it. I would appreciate if you could revert the spacing change though, it makes it quite hard to figure out what actually changed :)

**Comment by jesseflorig** [comment]
> it makes it quite hard to figure out what actually changed

Yeah, that makes sense. My apologies for submitting such an obnoxious PR. I just pushed an update restoring the tab spacing. However, my dev setup runs JS through [prettier](https://prettier.io/), so there are quite a few spacing updates (inside brackets and whatnot).

The only changes should be the `<GenericAlert />` component and any `showAlert` emits.

At this point, it might make sense to reject this PR and I can resubmit after making the changes to a fresh branch with my auto-formatting turned off.

In the future, it might be worth exploring adding a `.prettierrc` file to the project so your preferred code formatting is automatically handled (happy to help with this, too).

**Comment by rvazarkar** [comment]
If its not too much work, then lets do that, just to keep things consistent. Will a prettierrc configuration in the package.json work for you? I never thought to set one up

**Comment by jesseflorig** [comment]
> lets do that, just to keep things consistent. 

Cool, did you mean reject this PR or setup a prettier config? Both?

>Will a prettierrc configuration in the package.json work for you?

I defer to you, its personal preference really. It can be a prettier key in `package.json` or a separate config file. I tend to lean toward a separate file for separation of concerns, but it doesnt _really_ matter.

**Comment by rvazarkar** [comment]
I meant both, just because its hard to review a PR with so many changes, and I know the actual intentional changes are minimal. I'll put a .prettierrc file in the root of the project. 

{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": true,
  "singleQuote": true
}

Does that look right?

**Comment by jesseflorig** [comment]
Closing to re-apply changes without changing code format.

**Pull request closed without merging**
