### PR TITLE
Add parameter LocalAdminGroupName to Invoke-BloodHound.

### PR DESCRIPTION
**Pull request by ClementNotin**
When domain computers are configured in a different locale than English, the "Administrators" group is [localized](https://social.technet.microsoft.com/wiki/contents/articles/13813.localized-names-for-administrator-account-in-windows.aspx) (e.g. "Administrateurs" in French), it can also be renamed on purpose. It causes Get-NetLocalGroup to fail since it tries to enumerate the member by the wrong name, therefore some adminTo relations are missed.
This commit adds a new flag to Invoke-BloodHound: _-LocalAdminGroupName_ to indicate the expected localized name in the domain (the default is of course "Administrators'). If the given name is not found on a target computer (e.g. there is a few English computers in a mostly French domain), Get-NetLocalGroup is able to properly enumerate all the groups, identify the admin one through its -544 SID, and retry with the correct name.

I tested this change on a large production domain with the majority of computers localized in French ("Administrateurs") among a few in English: it discovered many more admin relations and there were none missing (i.e. no regression, it also means that it properly fallback to discovering the local admin group name for english computers). The collection duration was the same.

Please let me know if you prefer that I base this on the dev branch (instead of master).

I ported this change on Get-NetLocalGroup from this PR: https://github.com/PowerShellMafia/PowerSploit/pull/252

### CODE REVIEW

**Comment by rvazarkar** [comment]
This is clever. I'm not going to merge this in currently because the C# ingestor is nearing completion, but I am going to adapt the code to the new version so it should work there

**Comment by rvazarkar** [comment]
One problem I do have with this, is that it results in 2 API calls instead of one per computer, which isn't the best behavior. Going to see if I can come up with a solution that minimizes network requests

**Comment by ClementNotin** [comment]
Glad you like it! Do you intend to replace the PSH ingestor by the C# one?

Regarding the API calls, actually, if the name is correct there is still only 1 API call. If the name is incorrect it will do 3 calls (1/ get members with the wrong name, 2/ list groups, 3/ get members with the correct name).
Of course it would be best to query by SID, instead of name, but I'm unsure such API exists. I guess it would have been implemented already in PowerView.
If you find a better solution, we could port it to PowerView.

**Comment by rvazarkar** [comment]
Yes the PSH ingestor will eventually be replaced by the C# one

**Comment by ClementNotin** [comment]
That's interesting to hear! Let me know if you need help to implement it, in fact I am more familiar with C# than PSH.

**Comment by rvazarkar** [comment]
After a lot of tinkering, came up with a much more reliable method of querying this data. Will share soon!

**Comment by ClementNotin** [comment]
Awesome 👍 
Looking forward to know!

**Comment by rvazarkar** [comment]
@ClementNotin any chance I could get you to join the BloodHound slack channel so we can talk directly? =)

https://bloodhoundgang.herokuapp.com/

**Comment by ClementNotin** [comment]
Look like a phishing, but I'll bite :)

**Pull request closed without merging**
