### PR TITLE
Fixed cypher queries that broke High Value Targets stats

### PR DESCRIPTION
**Pull request by slemire**
This is a fix for bug #523

### CODE REVIEW

**Comment by rvazarkar** [comment]
The queries are setup the way they are to respect edge filtering, which this PR breaks

**Comment by yellow-starburst** [comment]
Is there another way to fix high value stats?

**Comment by yellow-starburst** [comment]
> The queries are setup the way they are to respect edge filtering, which this PR breaks

Is there another way to fix high value stats?

**Review by rvazarkar — COMMENTED** [review]
lgtm

**Review by rvazarkar — APPROVED** [review]

**Comment by rvazarkar** [comment]
I realize this isn't the right place to support edge filtering anyways, so I'll merge this. Thanks for the MR!

**Pull request merged**
