### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by Root-DE**

### CODE REVIEW

**Comment by JonasBK** [comment]
Hi @Root-DE,

Thanks for pointing out this this typo. Will you send this comment so I can accept the PR?

_I have read the CLA Document and I hereby sign the CLA_

Totally cool if you do not want to. Then, I will fix the typo :)

**Review by JonasBK — APPROVED** [review]

**Comment by JonasBK** [comment]
I believe it has something to do with the email of your commit not being associated with your user.. 

image

I think it will be fixed if you add this email address here to your account: 58123348+Root-DE@users.noreply.github.com

Here is how to do it:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

Completely cool if you do not want to do that. Then I will simply add the change :)

**Comment by Root-DE** [comment]
I can't add this email because "Error adding 58123348+Root-DE@users.noreply.github.com: email is already in use"
I guess this is the case since i have email privacy turned on
And the commit email is the same (see here https://github.com/BloodHoundAD/BloodHound/commit/2979e8ef2dbc4ad69d446b3d8db42cb4a4946619.patch) so i guess unless you have an idea you have to add it manually

**Comment by JonasBK** [comment]
Hmm.. odd.. Should I just close the PR and add the change myself or do you want troubleshoot it?

**Comment by Root-DE** [comment]
Yes

**Pull request closed without merging**
