### PR TITLE
Added Installation Instructions and Troubleshooting for Windows + New SharpHound Flags

### PR DESCRIPTION
**Pull request by LuemmelSec**
I ran across several issues lately, often times related to the neo4j setup on Windows systems.

I documented and added them accordingly with screenshots and solutions.

Also did an update to the OpenJDK installation and an alternative to the Oracle implementation.

Lastely created a video where everything is covered as well:

https://www.youtube.com/watch?v=PgjtvxA-MMk

### CODE REVIEW

**Comment by LuemmelSec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martinsohn** [comment]
Great instructions! A few notes after following it:

- The NEO4J_CONF and NEO4J_HOME variables are not present in my setup, yet no errors were outputted and Neo4j works.
- The directory which the Neo4j zip file is unzipped to and installed from ("install-service") will be the directory of the Neo4j services. It can be recommended to unzipped it to "Program Files\Neo4j\" prior to service installation.

**Comment by LuemmelSec** [comment]
> Great instructions! A few notes after following it:
> 
> * The NEO4J_CONF and NEO4J_HOME variables are not present in my setup, yet no errors were outputted and Neo4j works.
> * The directory which the Neo4j zip file is unzipped to and installed from ("install-service") will be the directory of the Neo4j services. It can be recommended to unzipped it to "Program Files\Neo4j" prior to service installation.

Thanks for looking through the doc, much appreciated.
The two environment variables do not get auto created. I ran into the issues several times, always in Commando VMs. I included screenshots in the final documentation, but didn't run into the problem during the final recording of the video. However in any case creating the two variables made things work. I guess it is due to the old neo4j installation that comes shipped with the CommandoVM might be the culprit. If everything works fine, even better. But if you run into it, the solution is here.

I everytime have something like c:\tools where I put all my stuff. But I think that is something of a personal decision.
I can suggest that, but are there any benefits to explictly put it there?

**Comment by LuemmelSec** [comment]
I seem to be to dumb to split PRs.
So this PR also includes the changes needed to comply to the SharpHound addition for the Local Admin Session Enumeration:
https://github.com/BloodHoundAD/SharpHoundCommon/pull/47
https://github.com/BloodHoundAD/SharpHound/pull/40

image

**Comment by JonasBK** [comment]
Hey @LuemmelSec,

Thanks for this super awesome contribution! 

We will release a small 4.3.1 update very soon and would like to have your changes to the Windows installation included. We also want to merge in your new SharpHound flags but need more time to review the changes, so that will be in a later release.

Would you be able to split this PR into two, such that the changes to the Windows installation can be merged into 4.3.1?

**Comment by LuemmelSec** [comment]
Hi @JonasBK I tried to do so :)
Please see PRs 
664: https://github.com/BloodHoundAD/BloodHound/pull/664
665: https://github.com/BloodHoundAD/BloodHound/pull/665

Cheers
Dan

**Comment by JonasBK** [comment]
Awesome, Dan!
Thanks a lot for this great contribution! It is super helpful with the video as well :)

**Pull request closed without merging**
