### PR TITLE
Refactored Alert

### PR DESCRIPTION
**Pull request by jesseflorig**
Overview of changes:

- Converted `Alert.jsx` to a functional component using React Hooks
- Extended `Alert.jsx` to accept` type` and `timeout`
- Updated `showAlert` emitter events

Redux of the [failed PR](https://github.com/BloodHoundAD/BloodHound/pull/249).

### CODE REVIEW

**Comment by rvazarkar** [comment]
This is much much easier to look through, thank you! I appreciate the work you did to do this twice. I'm going to test this out and understand the changes and then I'll merge the PR

**Comment by jesseflorig** [comment]
No problem! Happy to help where able. In the future I think it would be great to add [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) and [reducers](https://reactjs.org/docs/hooks-reference.html#usereducer).

**Comment by rvazarkar** [comment]
I actually have PropTypes scattered throughout the code base, I just haven't been consistent with it =(

**Comment by jesseflorig** [comment]
Ah nice, I didn't think to check. I'll keep that in mind when refactoring things.

**Comment by rvazarkar** [comment]
Sorry this took so long, merged in 👍

**Pull request merged**
