### PR TITLE
Add instructions to use the JWT from the az cli

### PR DESCRIPTION
**Pull request by christophetd**

### CODE REVIEW

**Comment by christophetd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by christophetd** [comment]
Hello, any thoughts on getting this merged? cc @rvazarkar @andyrobbins

**Comment by andyrobbins** [comment]
Thank you for this PR, and please accept my apologies for not reviewing and merging this sooner

**Review by andyrobbins — APPROVED** [review]
LGTM

**Pull request merged**
